### ISSUE TITLE
error in npm

### ISSUE THREAD

**Issue by pipinoloco** [michnovka/ccxt-trading-cp#1]
![errocompilando](https://user-images.githubusercontent.com/29177517/35897018-f71b4bd2-0b9d-11e8-8d52-0881d8e14ef7.JPG)

**Comment by michnovka** [comment]
Hi, your config.json is buggy.

Please upload your config.json here and just replace all API keys and API secrets with XXXXXXXXXXXXXXXXXXXXXXXXXXX. I will add some better error messages for invalid JSON config.

As for your 2nd error, you are trying to install ccxt-trading-cp again inside itself. This is not possible, use `npm update` instead if you want to fetch the latest version.

**Comment by michnovka** [comment]
I have already added better error formatting, check version 1.2.2
