### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by normanu** [michnovka/ccxt-trading-cp#2]
When adjusting the config file I keep getting,

TypeError: Cannot read property '0' of undefined

What could this be?

**Comment by michnovka** [comment]
unfortunately without config file I cant say. paste config.json here and just replace keys and secrets with XXXXXXX

**Comment by rayzloutlook** [comment]
{
  "exchanges_unencrypted": [
    {
      "exchange": "kraken",
      "inactive": 1,
      "apiKey": "XXXXXXXXXXXXXXXX",
      "apiSecret": "XXXXXXXXXXXXXXXXXXXXX"
    }
  ],
  "exchange_for_fiat": "okcoinusd"
}

**Comment by rayzloutlook** [comment]
i met same situation, please help

**Comment by michnovka** [comment]
I have fixed this issue, please update and try again
